#%%
from dotenv import load_dotenv
load_dotenv()
from crewai import LLM ,Agent,Task,Crew
llm=LLM(
    model="gemini/gemini-2.5-flash",
    temperature= 0.2
)
finance_agent=Agent(
    role= " Financial Intelligence and Cost Optimization Analyst",
    goal="To evaluate the financial feasibility of operational decisions, optimize resource utilization, estimate transportation and logistics costs, identify budget risks, and provide financially sustainable recommendations that align with organizational objectives while maintaining operational efficiency",
    backstory="""The Finance Agent was developed to serve as the financial intelligence layer within the AgentMesh ecosystem. In modern logistics operations, decisions are often made based on speed, availability, or operational convenience, resulting in hidden costs, budget overruns, and inefficient resource allocation.
    The Finance Agent continuously analyzes operational plans generated by other agents and evaluates their financial impact before execution. It specializes in transportation cost estimation, budget validation, resource cost analysis, operational expenditure assessment, and financial risk identification.
    Rather than simply calculating expenses, the Finance Agent acts as a strategic financial advisor for the organization. It collaborates with Logistics, Risk, and Operations Agents to ensure that every proposed action is economically viable, resource-efficient, and aligned with organizational priorities.
    When multiple alternatives are available, the Finance Agent compares cost-benefit tradeoffs, identifies the most financially sustainable option, and provides transparent reasoning along with confidence assessments. Its objective is not to minimize cost at all times, but to maximize value while maintaining operational stability and long-term efficiency.""",
    verbose=False,
    llm = llm,
    allow_delegation=False
)

finance_task=Task(
    description="""Analyze the shipment plan and evaluate its financial feasibility. Estimate transportation, warehouse, and resource costs, assess budget compliance, identify financial risks, and recommend the most cost-effective option with clear reasoning.Provide responses in a professional business-report format.
    Do not use emojis, special symbols, decorative formatting, markdown icons, or conversational language.
    IMPORTANT INSTRUCTIONS:
                        Return output as plain text only.

                        Forbidden:
                        - Emojis
                        - Unicode icons
                        - Markdown formatting
                        - Decorative separators
                        - Bullet symbols
                        - Tables

                        Use only simple professional business language.""",
    expected_output="""Financial Analysis Report

                        1. Estimated Total Cost
                        2. Transportation Cost Breakdown
                        3. Resource Cost Breakdown
                        4. Budget Compliance Status
                        5. Financial Risk Assessment
                        6. Cost-Efficiency Score
                        7. Alternative Cost-Optimized Options (if applicable)
                        8. Confidence Score
                        9. Financial Recommendation
                        10. Detailed Reasoning Behind the Recommendation
""",
    agent=(finance_agent),
    verbose=False
)
import asyncio

print("FILE STARTED")

async def main():
    print("MAIN STARTED")

    crew = Crew(
        agents=[finance_agent],
        tasks=[finance_task],
        verbose=True
    )

    print("BEFORE KICKOFF")

    result = await crew.kickoff_async()

    print("AFTER KICKOFF")
    print(result)

if __name__ == "__main__":    asyncio.run(main())