#%%
from dotenv import load_dotenv
load_dotenv()
from crewai import Agent,Task,LLM,Crew
llm=LLM(
    model="gemini/gemini-2.5-flash",
    temperature=0.5
)
risk_agent=Agent(
    role="Senior Logistics Risk Assessment and Operational Resilience Analyst",
    goal="Identify, evaluate, and predict operational, logistical, and resource-related risks before execution. Assess potential disruptions, delays, capacity constraints, and operational vulnerabilities to help the organization make reliable and resilient decisions.",
     backstory="""The Risk Agent serves as the operational risk intelligence layer within the AgentMesh ecosystem. Modern logistics operations face uncertainties such as route disruptions, warehouse congestion, resource shortages, delivery delays, and unforeseen operational failures.
        The Risk Agent continuously evaluates plans generated by other agents and identifies potential threats that may impact execution. It specializes in risk detection, disruption analysis, capacity monitoring, dependency assessment, and operational resilience evaluation.
        Rather than reacting to failures after they occur, the Risk Agent proactively identifies vulnerabilities and provides risk assessments, mitigation strategies, and confidence evaluations before execution. It collaborates with Logistics, Finance, and Operations Agents to ensure that decisions are not only efficient and cost-effective but also reliable under uncertain conditions.
        The objective of the Risk Agent is to minimize operational failures, improve organizational resilience, and provide transparent risk intelligence that supports informed decision-making.""",
    verbose= False,
    llm=llm)
risk_tasks=Task(
    description="Analyze the proposed logistics plan and identify potential operational risks, delays, resource constraints, capacity issues, and execution vulnerabilities. Evaluate the likelihood and impact of each identified risk and provide mitigation recommendations to improve operational reliability and resilience.",
    agent=risk_agent,
    expected_output="""Risk Assessment Report
                        1. Overall Risk Level
                        2. Identified Risks
                        3. Risk Probability
                        4. Risk Impact Assessment
                        5. Capacity Risk Analysis
                        6. Resource Risk Analysis
                        7. Operational Vulnerabilities
                        8. Recommended Mitigation Actions
                        9. Confidence Score
                        10. Final Risk Recommendation""",
    capabilities="""- Delay Prediction
                    - Route Risk Analysis
                    - Capacity Monitoring
                    - Resource Shortage Detection
                    - Operational Risk Assessment
                    - Vulnerability Detection
                    - Disruption Analysis
                    - Risk Scoring
                    - Mitigation Recommendation
                    - Resilience Evaluation""",
    verbose=False
                    )
import asyncio

async def main():
    crew = Crew(
        agents=[risk_agent],
        tasks=[risk_tasks],
        verbose=False
    )
    result = await crew.kickoff_async()
    print(result)

if __name__ == "__main__":
    asyncio.run(main())